### ISSUE TITLE
我想在服务器上部署test一下，但是生成的IP地址是内网的，可以生成公网IP地址吗？

### ISSUE THREAD

**Issue by Geeker9** [ww55235/vue-music#1]
您好，感谢您的工作！这是我第一次学习并尝试基于Vue的项目，我在服务器上部署时，发现项目使用的IP地址是内网IP地址，请问可以在那里可以修改为公网的IP地址呢？

**Comment by ww55235** [comment]
您好!你可以用node.js 生成一个服务器,然后把 项目打包后的文件 dist 放在public下, 然后改一下请求的路径。然后NeteaseCloudMusicApi下的接口你需要放进去,启动这个服务器。
![image](https://user-images.githubusercontent.com/61737514/169475480-3374340f-d973-4008-a404-3e5dc4c37074.png)

**Comment by ww55235** [comment]
您好!你可以用node.js 生成一个服务器,然后把 项目打包后的文件 dist 放在public下, 然后改一下请求的路径。然后NeteaseCloudMusicApi下的接口你需要放进去,启动这个服务器。
![image](https://user-images.githubusercontent.com/61737514/169476016-a11cf848-3791-4274-8472-9ccc3a321f7d.png)

**Comment by ww55235** [comment]
我专门搭了一个node.js 的服务器, 希望能帮到你。

**Comment by ww55235** [comment]
这个是后台的服务器地址https://github.com/ww55235/vue-music-server 前端项目也更新了一些代码,希望能帮到你

**Comment by Geeker9** [comment]
谢谢您的回复！
